FROM ubuntu:18.04
RUN apt-get update \
 \
 && apt-get install -y ca-certificates git \
 && git clone https://github.com/czcorpus/kontext.git /opt/kontext/ \
 && cd /opt/kontext/scripts/install \
 && chmod +x install.ubuntu.sh \
 && sh ./install.ubuntu.sh
