FROM ubuntu:18.04
RUN apt-get update \
 \
 && apt-get install -y ca-certificates git curl gnupg \
 && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
 && apt-get -y install nodejs \
 && npm link webpack \
 && npm link webpack-cli \
 && git clone https://github.com/czcorpus/kontext.git /opt/kontext/ \
 && cd /opt/kontext/scripts/install \
 && chmod +x install.ubuntu.sh \
 && sh ./install.ubuntu.sh
