version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: copens_redis
  memcached:
    image: memcached
    restart: always
    container_name: copens_memcached
    entrypoint:
      - memcached
      - -m 2000
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  copens_db:
    container_name: copens_db
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=copens
      - MYSQL_DATABASE=copens
      - MYSQL_USER=copens
      - MYSQL_PASSWORD=copens
    volumes:
      - ./config/mariadb:/etc/mysql/conf.d
      - mariadb-volume:/var/lib/mysql
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  web:
    build: .
    volumes:
      - cwb-volume:/app/COPENS/cwb/
    environment:
      - PYTHONUNBUFFERED=0
    tty: true
    container_name: copens_web
    depends_on:
      - copens_db
      - memcached
    restart: always
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file

volumes:
  cwb-volume:
  mariadb-volume:


