version: '3'

services:
  memcached:
    image: memcached
    restart: always
    container_name: copens_memcached
    entrypoint:
      - memcached
      - -m 2000
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  copens_db:
    container_name: copens_db
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=copens
      - MYSQL_DATABASE=copens
      - MYSQL_USER=copens
      - MYSQL_PASSWORD=copens
    volumes:
      - ./config/mariadb:/etc/mysql/conf.d
      - mariadb-volume:/var/lib/mysql
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  web:
    build: .
    volumes:
      - cwb-volume:/app/COPENS/cwb/
    environment:
          - PYTHONUNBUFFERED=1
    tty: true
    container_name: copens_web
    depends_on:
      - copens_db
      - memcached
#    command: >
#      bash -c "python manage.py makemigrations --noinput
#      && python manage.py migrate --noinput
#      && python manage.py collectstatic --noinput
#      && uwsgi --uid root --master --http 0.0.0.0:8000 --module COPENS.wsgi
#      --process 4 --manage-script-name --mount=/copens2=COPENS/wsgi.py"
#    #      && python -u manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file

volumes:
  cwb-volume:
  mariadb-volume:


