version: '3'

services:
#  nginx:
#    image: nginx
#    container_name: copens_nginx
#    restart: always
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - web
  web:
    build: .
    container_name: copens_web
    command: apachectl -D FOREGROUND
    restart: always
#    stdin_open: true
#    tty: true
    ports:
      - "80:80"


